### ISSUE TITLE
1.9 Client Bad Packet disconnect when getting chunks with signs

### ISSUE THREAD

**Issue by Z609** [HexagonMC/BungeeCord#2] opened 2016-03-03 03:27 UTC
22:25:08 [WARNING] [Z609] <-> DownstreamBridge <-> [Server1] - bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.SetCompression 70 Protocol GAME Direction TO_CLIENT
22:25:08 [SEVERE] io.netty.handler.codec.DecoderException: net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.SetCompression 70 Protocol GAME Direction TO_CLIENT
22:25:08 [SEVERE]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
22:25:08 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
22:25:08 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
22:25:08 [SEVERE]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
22:25:08 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
22:25:08 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
22:25:08 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
22:25:08 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
22:25:08 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
22:25:08 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
22:25:08 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
22:25:08 [SEVERE]     at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
22:25:08 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
22:25:08 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
22:25:08 [SEVERE]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
22:25:08 [SEVERE]     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
22:25:08 [SEVERE]     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
22:25:08 [SEVERE]     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
22:25:08 [SEVERE]     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
22:25:08 [SEVERE]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
22:25:08 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
22:25:08 [SEVERE]     at java.lang.Thread.run(Unknown Source)
22:25:08 [SEVERE] Caused by: net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.SetCompression 70 Protocol GAME Direction TO_CLIENT
22:25:08 [SEVERE]     at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:37)
22:25:08 [SEVERE]     at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
22:25:08 [SEVERE]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
22:25:08 [SEVERE]     ... 21 more
22:25:08 [INFO] [Z609] disconnected with: DecoderException : net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.SetCompression 70 Protocol GAME Direction TO_CLIENT @ io.netty.handler.codec.MessageToMessageDecoder:99
22:25:08 [INFO] [Z609] disconnected with: [Proxy] Lost connection to server.
22:25:08 [INFO] [Z609] <-> DownstreamBridge <-> [Server1] has disconnected
22:25:08 [INFO] [Z609] -> UpstreamBridge has disconnected

Not sure what this has to do with. I'm connecting to a 1.8 server (I'm not really concerned about 1.7) with a 1.9 client.

What might this have to do with, and might there be a fix for this? Using 15.

**Comment by i9hdkill** [comment] 2016-03-03 03:31
Hi,
you cannot connect with 1.9 to 1.8.
This bungee version only allows you to have 1.7, 1.8 and 1.9 servers at the same time in your network.
This is not a protocol build or similiar.

**Comment by Spurlex** [comment] 2016-03-03 03:40
I get this same error when connecting to a 1.9 server with 1.9.

22:39:10 [INFO] [Skull] <-> ServerConnector [Hub-1.9] has connected
22:39:10 [WARNING] [Skull] <-> DownstreamBridge <-> [Hub-1.9] - bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.SetCompression 70 Protocol GAME Direction TO_CLIENT
22:39:10 [SEVERE] io.netty.handler.codec.DecoderException: net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.SetCompression 70 Protocol GAME Direction TO_CLIENT
22:39:10 [SEVERE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
22:39:10 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
22:39:10 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
22:39:10 [SEVERE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
22:39:10 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
22:39:10 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
22:39:10 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
22:39:10 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
22:39:10 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
22:39:10 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
22:39:10 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
22:39:10 [SEVERE] 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
22:39:10 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
22:39:10 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
22:39:10 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
22:39:10 [SEVERE] 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
22:39:10 [SEVERE] 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
22:39:10 [SEVERE] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
22:39:10 [SEVERE] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
22:39:10 [SEVERE] 	at java.lang.Thread.run(Thread.java:745)
22:39:10 [SEVERE] Caused by: net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.SetCompression 70 Protocol GAME Direction TO_CLIENT
22:39:10 [SEVERE] 	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:37)
22:39:10 [SEVERE] 	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
22:39:10 [SEVERE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
22:39:10 [SEVERE] 	... 19 more
22:39:10 [INFO] [Skull] <-> DownstreamBridge <-> [Hub-1.9] has disconnected

**Comment by i9hdkill** [comment] 2016-03-03 03:46
Check you server.properties and verify that the network-compression threshold is set to 256

**Comment by Spurlex** [comment] 2016-03-03 03:48
It is. I've regenerated my configs and it works. Must be something in my configs.

**Comment by i9hdkill** [comment] 2016-03-03 03:51
Could post your bungee config, server.properties?

**Comment by i9hdkill** [comment] 2016-03-03 03:53
Okay, we will look into it. Thank for reporting.

**Comment by Spurlex** [comment] 2016-03-03 04:30
Turns out this Bungee doesnt seem to like any of my pre-1.9 maps. I can give you a map to test.

**Comment by Spurlex** [comment] 2016-03-03 04:43
@i9hdkill Found the cause. Signs crash it and wont let you rejoin.

**Comment by PsychoLynx** [comment] 2016-03-03 08:06
Same thing happens here. Running a 1.9 Spigot server as our lobby with ProtocolSupport. 1.7.10 and 1.8.9 clients can join without problem, but 1.9 gets kicked upon starting to load the world.

**Comment by kwakmantim** [comment] 2016-03-03 09:16
Same problem as @PsychoLynx

**Comment by Aangiix3** [comment] 2016-03-03 11:28
Any news on this?

**Comment by i9hdkill** [comment] 2016-03-03 13:39
We were able to reproduce this. These are definetely signs from 1.8 (And probably 1.7) that are disconnecting the client.
Thank you for giving the hint.
We are on it.

**Comment by Spurlex** [comment] 2016-03-03 13:46
I don't know if its just signs. I've tried removing the signs from the world and it still occurs. Might wanna test with some 1.7/1.8 maps and see.

**Comment by i9hdkill** [comment] 2016-03-03 13:49
Does even happen when placing signs with 1.9. We will do some further testing.

Did you remove them with:
//replace 68,63 0 ?
Wallmounted signs and free standing signs have different ids.

**Comment by ghacproductions** [comment] 2016-03-03 15:51
I think I found the problem, now looking how to fix it.

**Comment by ghacproductions** [comment] 2016-03-03 16:23
Update: found the problem, going to fix now.

**Comment by kwakmantim** [comment] 2016-03-03 17:32
@ghacproductions Can you fix the problem that you can't join using 1.9 with protoclsupport in the Lobby? You're fix removes all the spam in de console but i'm still unable to join; https://snapr.pw/i/d506b7650f.png

**Comment by i9hdkill** [comment] 2016-03-03 18:44
We don't officially support ProtocolSupport/ProtocolSupportBungee.
We will release a new version soon in the release section that fixes the sign issue and some other issues.

**Comment by kwakmantim** [comment] 2016-03-03 18:47
But why does it work on the normal bungeecord build and not on this one?

**Comment by i9hdkill** [comment] 2016-03-03 19:08
It should be fixed now. If it's still not working, please post an exact way how to reproduce the issue.
In addidtion to that, the prioritylist now works with 2 and more servers.

**Comment by PsychoLynx** [comment] 2016-03-03 19:13
@i9hdkill Seems to work on our lobby server now. Thank you so much! I've been waiting all day to update :)

**Comment by ghacproductions** [comment] 2016-03-03 19:25
This is closed by https://github.com/HexagonMC/BungeeCord/releases/tag/v21.

Please also thank @Zartec as he might be very sad otherwise.

**Closed by ghacproductions** 2016-03-03 19:25 UTC
Labels: bug

**Comment by James137137** [comment] 2016-03-03 19:35
bug still seems to be present on my end when placing a sign
http://pastebin.com/zi4ukrZy

**Comment by Zartec** [comment] 2016-03-03 19:40
Just a little moment...

**Comment by ghacproductions** [comment] 2016-03-03 19:40
Whoops, merging is bad.

**Comment by James137137** [comment] 2016-03-03 19:52
testing now from e6484778061906f0bb837096387d53087a49bf33 commit

**Comment by James137137** [comment] 2016-03-03 19:55
at e6484778061906f0bb837096387d53087a49bf33 bug still present

**Comment by kwakmantim** [comment] 2016-03-03 19:55
It works :O Thanks @ghacproductions @Zartec @i9hdkill <3

**Comment by kwakmantim** [comment] 2016-03-03 20:02
EDIT: It looks likes the problem now occurs on 1.7 https://snapr.pw/i/31addbca60.png (on joining)

**Comment by ghacproductions** [comment] 2016-03-03 20:06
What version are you using? 1.7.10 over here works fine.

**Comment by kwakmantim** [comment] 2016-03-03 20:07
1.7.10 (1.7.2 works fine tho.)

**Comment by kwakmantim** [comment] 2016-03-03 20:08
Oh wait it just took a bit longer

**Comment by ghacproductions** [comment] 2016-03-03 20:09
I know see what you mean. Wait one moment please, should be resolved in a moment.

**Comment by kwakmantim** [comment] 2016-03-03 20:20
Thanks works pefect now :)

**Comment by vovanre** [comment] 2016-03-03 20:21
hmm, last update behaves strangely:
On bungee:
http://joxi.ru/E2pvvpKIBY76Xr?d=1
On server:
http://joxi.ru/MAj00BQSvajg3m?d=1

If i connect directly - all ok

**Comment by ghacproductions** [comment] 2016-03-03 20:28
Try v25 please - Works fine, I tested it with 1.7.10, 1.8.9 and 1.9.

**Comment by vovanre** [comment] 2016-03-03 20:44
Yep, all done.

**Comment by James137137** [comment] 2016-03-03 20:44
looks fine on first test. Doing more

**Comment by ghacproductions** [comment] 2016-03-03 20:57
Perfect, I'll lock conversation now. When finding some other bugs, please open a new issue.

**Comment by ghacproductions** [comment] 2016-03-03 22:57
@PsychoLynx  @kwakmantim  We just tested this BungeeCord with the latest ProtocolSupport (based on Spigot 1.9), works pretty good at all for us.

**Comment by James137137** [comment] 2016-03-04 04:56
also tested with the latest ProtocolSupport and without. no problems as of yet
