### ISSUE TITLE
Netty error when connecting to thermos

### ISSUE THREAD

**Issue by RoboJsckPlsys** [HexagonMC/BungeeCord#179] opened 2017-09-19 21:16 UTC
### What Hexacord version are you using? Post the output of /bungee
Latest version. (v170)

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
We are only using Bungee Perms

### How can we reproduce the error/bug? 
Attempting to connect to a Thermos 1.7.10 server with more than 70 mods Installed client and server side 

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
https://pastebin.com/dCWHe5Xy

### In addidtion to that, please explain your issue as detailed as possible.
When you attempt to join a Thermos 1.7.10 server with more than around 60-70 mods you are kicked to the fall back lobby server (Vanilla spigot) I think it is an issue with the amount of packets allowed by the Hexagon Version

**Comment by i9hdkill** [comment] 2017-09-19 21:29
At the moment we do not support negative packet ids. (Broke with 1.11 or 1.12 update)
That's a won't fix issue, unless someone prepares a PR for it.

**Comment by RoboJsckPlsys** [comment] 2017-09-19 21:36
But when testing earlier it worked with 1.11 and ViaVersion plugins. Why is this not the case with 1.12

**Comment by i9hdkill** [comment] 2017-09-19 21:56
Broke somewhere here:
https://github.com/dogboy21/BungeeCord/commit/16d261553c1a648ce38101bda19b7166d1ca5a41#diff-f5da6738ad3c03e59c357db9fd022745L226

**Comment by spannerman79** [comment] 2017-09-27 07:33
Duplicate of #152 

@RoboJsckPlsys Follow https://github.com/HexagonMC/BungeeCord/issues/152#issuecomment-303656327 & drop 1.12.x support or drop 1.7.10 servers

**Comment by i9hdkill** [comment] 2018-07-31 19:55
This issue was fixed lately

**Closed by i9hdkill** 2018-07-31 19:55 UTC
