### ISSUE TITLE
Problem with Rending from bungeecord

### ISSUE THREAD

**Issue by CyberSpongie** [HexagonMC/BungeeCord#95] opened 2016-11-08 16:20 UTC
Hello so this bug had been a problem on spigot side of bungeecord and HexagonMC bungeecord so there this mod called "AdventureBackpack Mod" and this mod works great on Cauldron/KCauldron/Thermos but when these server jar's get connect to this bungeecord or spigot 1.7.10 bungeecord you cannot see your backpack or interact with it, is this a problem with bungeecord and i am wondering if you guys can fix this here are some reports that i found that can explain in more detail
Report: https://github.com/runescapejon/AdventureBackpack2/issues/20
Report: https://github.com/Darkona/AdventureBackpack2/issues/91
here is the mod's 
Darkona: https://github.com/Darkona/AdventureBackpack2
and 
runescapejon (continuation of the mod): https://github.com/runescapejon/AdventureBackpack2
please help me with this problem it's really annoying and i hope you understand thanks you

**Comment by Eufranio** [comment] 2016-11-30 23:58
This is the same bug as Thaumcraft and OpenBlocks (glider) has, I think... Just use forced hosts until the problem is fixed...

**Comment by jon100456** [comment] 2016-12-01 03:54
Yea that is why i believe it's bungeecord issue waitng for a fix i do not have a domain or subdomain so i am unable to use force host

**Comment by ccxufo** [comment] 2016-12-01 04:16
It's not support all packets with mod.

**Comment by jon100456** [comment] 2016-12-01 06:19
do you think you can fix this problem? or is there some how a fix for this mess? 
thanks

**Comment by KasperFranz** [comment] 2016-12-01 07:25
get direct connect - buy a domain and set that up, else don't use bungee ;)

**Comment by jon100456** [comment] 2016-12-01 09:43
i use it for my other servers is that i use about 2 servers for modded that why i need this fix aww man come on

**Comment by KasperFranz** [comment] 2016-12-01 09:54
it isn't a easy fix - it is a quite large thing - and i would be surprised if anyone fixes it since the "easy" fix is to just use direct connet

**Comment by MJRLegends** [comment] 2016-12-01 09:55
Yeah it would be great if anyone could even attempt a work around for itz

**Comment by jon100456** [comment] 2016-12-01 15:53
I'm just hoping that someone will fix this, cause what the point of having bungeecord to 1.7 when if things like this is not going to get fix

**Comment by i9hdkill** [comment] 2016-12-01 16:27
We will definitely not fix it. We are using this fork to support Pixelmon 1.7 only.

If mods doing weird stuff on packet level, it's not bungees concern.
You might talk to the mod author or use up to date 1.10/1.11 mods where this behaviour might be fixed/changed

**Closed** 2019-07-05 15:19 UTC
