### ISSUE TITLE
v147 and 145: KCauldron, 1.7.10 : Proxy disconnects

### ISSUE THREAD

**Issue by raum266** [HexagonMC/BungeeCord#152] opened 2017-05-22 03:47 UTC
I was using an older version (v135) and figured I should probably update. After updating, all servers could still connect except the 1.7.10 Cauldron server. It'd connect on the MC server, then immediately disconnect with no error. 

Proxy showed the following:

23:15:19 [FINE] [COMPLETE Client -> Bungee][SENDING: HandshakeAck]
23:15:19 [FINE] [DONE Server <- Bungee][RECEIVED: HandshakeAck]
23:15:19 [SEVERE] [Koopafan75] <-> DownstreamBridge <-> [SCM] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException
  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
  at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
  at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017)
  at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
  at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
  at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException
23:15:19 [INFO] [Koopafan75] <-> DownstreamBridge <-> [SCM] has disconnected
23:15:19 [INFO] [Koopafan75] <-> ServerConnector [Survival] has connected

This behaviour occurred with both 147 and 145; I didn't have much more time to test, so I just went back to 135 and the problem no longer exists.

**Comment by KasperFranz** [comment] 2017-05-22 06:48
The issue is also present with Thermos

**Comment by i9hdkill** [comment] 2017-05-22 19:50
Probably all 1.7 Forge instances with IP-Forwarding on. We will look into it.

**Comment by Eufranio** [comment] 2017-05-22 23:57
Same:
```
> 01:56:37 [SEVERE] [Gabrielbross] <-> DownstreamBridge <-> [BlackCraft] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException
> 01:56:37 [INFO] [Gabrielbross] <-> DownstreamBridge <-> [BlackCraft] has disconnected
```

**Comment by ghacproductions** [comment] 2017-05-23 10:43
Investigating now.

**Comment by ghacproductions** [comment] 2017-05-23 11:16
What exact setup are you using? It's working for me with Cauldron 1.7.10-1.1236.05.210 and v147 of our BungeeCord. IP-forwarding is enabled.

**Comment by Eufranio** [comment] 2017-05-23 11:17
Thermos build 58 for backend servers and HexaCord v145 is my setup...

**Comment by ghacproductions** [comment] 2017-05-23 11:22
@Eufranio 
I've just tested Hexacord v147 and Thermos Build 58 (Forge 1614), it still works.

**Comment by Eufranio** [comment] 2017-05-23 11:56
Hmm, something I believe that is interfering with it is Ars Magica 2 then (their effect/potion packets are larger than vanilla ones, and threw errors when I switched to Travertine), so...

**Comment by raum266** [comment] 2017-05-23 13:56
I'm using KCauldron 1614.201 ( https://repo.prok.pw/pw/prok/KCauldron/1.7.10-1614.201/KCauldron-1.7.10-1614.201-bundle.zip )

We are using several mods - obviously - but Ars Magica is not one of them.

I've got a bit of free time this morning, so I am going to go back and find out exactly which version of Bungee it stops working in.

**Comment by raum266** [comment] 2017-05-23 14:17
K, everything works up to v140 just fine. v141 disconnects immediately to a fallback server.

* v141's error added a small bit of info that did not exist in v147 :


`10:03:42 [FINE] [PENDINGCOMPLETE Client <- Bungee][RECEIVED: HandshakeAck]
10:03:42 [SEVERE] [Raum] <-> DownstreamBridge <-> [SCM] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: -26
  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
  at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
  at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017)
  at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
  at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
  at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -26
  at net.md_5.bungee.protocol.Protocol$DirectionData.createPacket(Protocol.java:365)
  at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:30)
  at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
  ... 23 more
10:03:42 [FINE] [PENDINGCOMPLETE Client -> Bungee][SENDING: HandshakeAck]
10:03:42 [FINE] [DONE Server <- Bungee][RECEIVED: HandshakeAck]
10:03:42 [FINE] [COMPLETE Client -> Bungee][SENDING: HandshakeAck]
10:03:42 [FINE] [DONE Server <- Bungee][RECEIVED: HandshakeAck]
10:03:42 [INFO] [Raum] <-> DownstreamBridge <-> [SCM] has disconnected
`

**Comment by ghacproductions** [comment] 2017-05-23 15:03
@raum266 
If it's still working with v140, then it cannot be a problem with forge-ipforwarding but must have to do something with the 1.12-pre-support (maybe conflicts with packets). This needs further investigation. Do you have any idea, what mod causes this?

**Comment by raum266** [comment] 2017-05-23 15:06
@ghacproductions I have not had time to play with individual mods yet (work picked up afterall. yay. :/) but I know Thaumcraft has had packet issues in the past.  We unfortunately use about 100 mods, however, so if it's NOT thaum, it may be a pain to test. Will provide more feedback once I can test some more.

**Comment by Eufranio** [comment] 2017-05-23 15:08
We're also running Thaumcraft.

**Comment by Eufranio** [comment] 2017-05-23 15:15
Our modpack: https://www.technicpack.net/modpack/blackcraft-server.591976

**Comment by Zilacon** [comment] 2017-05-24 08:33
Can confirm i am also having this issue. Had to downgrade to v140 to keep my sanity.
A fix to this would be great.

**Comment by raum266** [comment] 2017-06-08 00:46
K, Slight update : 

 It is the Thermal Dynamics (and friends) Mod causing this issue - removing it will fix the problem. Now, I have *NOT* had the chance to update the mods to newest version to see if it still causes this issue, but that is definitely what is causing it.

Also, I do not know which one of the mods it actually is, or all of them .. there's 5 total: Thermal Dynamics, Expansion and Foundation, MineFactoryReloaded, and CoFHCore.

**Comment by Proplex** [comment] 2017-06-08 11:47
@raum266 Without looking into it, I’d place a large bet that CoFHCore is causing the problems. That mod has a history of being a hassle to deal with.

**Comment by raum266** [comment] 2017-06-08 14:57
The most recent versions do not fix the issue. Hopefully @dogboy21's commit will correct it. I kinda like those mods.

**Comment by dogboy21** [comment] 2017-06-08 14:58
It's currently running on our servers without a single problem. I can connect to 1.7.10 servers with Thermos, 1.10 servers with Sponge and even 1.12 servers.

**Comment by raum266** [comment] 2017-06-08 14:58
@dogboy21 Are you also using the CoFH mods?

**Comment by dogboy21** [comment] 2017-06-08 15:00
Yes

CoFHCore-[1.7.10]3.1.3-327
ThermalDynamics-[1.7.10]1.2.0-171
ThermalExpansion-[1.7.10]4.1.3-246
ThermalFoundation-[1.7.10]1.2.5-115
MineFactoryReloaded-[1.7.10]2.8.1-174

**Comment by raum266** [comment] 2017-06-08 15:03
Awesome. I'll have to see if I can pull the changes and compile until an official release comes out with it. Thanks!

**Comment by raum266** [comment] 2017-06-09 14:43
It looks like your change went live, however still having the same issue. Going to attempt to downgrade the CoFH mods to your versions.

**Comment by i9hdkill** [comment] 2017-06-09 14:48
Can you connect to a 1.7 modded server without CoFHCore installed or to a 1.7 forge server with mods installe din general?
Guess the ip forwarding comit for forge 1.8+ broke 1.7 forge compability.

**Comment by raum266** [comment] 2017-06-09 14:49
@i9hdkill Yes: Without The CoFH mods, we can connect just fine.

**Comment by i9hdkill** [comment] 2017-06-09 14:50
Even with ip forwarding enabled? Weird, as is broke with this said commit.

**Comment by raum266** [comment] 2017-06-09 14:52
Ooh, I've not tried with this most recent version - sorry. I had just updated - restarting everything now without said mods to try.

**Comment by i9hdkill** [comment] 2017-06-09 14:53
Ah I see the issue. The official stance of bungee is, that it don't support custom package ids.(In this case negative ones).
But I remember that we pulled a PR that added support for this and probably got overwritten by that forwarding comit. We will look into it. @ghacproductions

**Comment by timr2000** [comment] 2017-06-26 01:43
Still got this issue.. -.-

**Comment by spannerman79** [comment] 2017-06-26 01:50
> Still got this issue.. -.-

@timr2000 if you looked at the [commit history](https://github.com/HexagonMC/BungeeCord/commits/master) you would know to wait.  Be thankful that Hexacord is offered freely.  If you are in such a rush to have this resolved then I'm sure that you can hire a java developer.

**Comment by Ismael-GT** [comment] 2017-08-04 12:13
I have the same problem, I hope it will be fixed soon as developers can.
The main feature for Hexagon it support the 1.7 so I think the developers can solve it and not will drop the 1.7 support from 1.12 or more.

Thanks for all.

**Comment by spannerman79** [comment] 2017-08-10 23:33
v161 was pushed a little while ago.
@ghacproductions does v161 resolve this or were the changes made only apply to MC 1.12 ?

**Comment by popcorn9499** [comment] 2017-08-11 04:29
Just figured I'd note that the latest update did nothing for 1.7.10 and the fml issues. I didnt expect it to nothing in the commit said anything

**Comment by timr2000** [comment] 2017-09-10 18:11
this will never be fixed i guess..

**Comment by popcorn9499** [comment] 2017-09-10 19:11
@timr2000 Dont think like that. Devs dont like people constantly nagging about this stuff. I'm sure they are looking at it but its probably not a priority. They haven't removed this issue so I figure they are probably just busy as of right now. Give it time.

**Comment by Proplex** [comment] 2017-10-09 22:54
Hey, can we get an official word on what's going on here? It's been months and still no public attempt at a fix. There are plenty of server administrators held back by this bug (myself included), and if fixing this is not important to you, it would be nice to know. 

I reached a point where supporting a 1.7.10 Forge server is migraine-inducing, and so knowing whether or not to hold out for a future bug fix or putting this server to rest would be great.

**Comment by spannerman79** [comment] 2017-10-09 22:56
@Proplex https://github.com/HexagonMC/BungeeCord/issues/179#issuecomment-330679310

**Comment by Proplex** [comment] 2017-10-09 23:01
Dope, thanks. Time to kill this dumb server.

**Comment by spannerman79** [comment] 2017-10-09 23:15
> if you just remove the Thermal & Co mods (COFH, MineFactory, etc),

Ah but in 1.7.10 TeamCoFH mods are bread and butter. Unless you are playing pure magic type mods it is "expected" to have at least one of TeamCoFH mods running.

**Comment by raum266** [comment] 2017-10-09 23:16
That's true. But unfortunately it's use 1.12 and no CoFH, or don't upgrade to 1.12, so far.

**Comment by spannerman79** [comment] 2017-10-09 23:20
The only suggestion that I can bring forward is to put this issue under [BountySource](https://www.bountysource.com/issues/45429961-v147-and-145-kcauldron-1-7-10-proxy-disconnects).

I am not sure how the HexagonMC dev feels about that.

**Comment by popcorn9499** [comment] 2017-10-09 23:49
If anyone cares I've been compiling that temp fix that i have to thank the guy who submited this here https://github.com/dogboy21/BungeeCord/commit/84396969e63aa5710f41fb01505064a9fe39ff4b 
Its currently seeming to work with minecraft 1.12.2. I have it being compiled as well. just figured id throw this out there https://github.com/popcorn9499/BungeeCord

**Comment by spannerman79** [comment] 2017-10-09 23:53
Oh ok @popcorn9499 
Does your build download the (I assume updated) modules as well?

**Comment by popcorn9499** [comment] 2017-10-09 23:54
Its just a clone of the hexagonmc bungee with that one commit added so i don't think so. It seems to be working either way

**Comment by popcorn9499** [comment] 2017-10-09 23:55
I was just trying to find a easy way to keep up to date with commits so i figured this would help me learn github abit more while making my life possibly simpler

**Comment by dogboy21** [comment] 2017-10-09 23:55
It's only a modified base, I've made no changes to the modules.

**Comment by popcorn9499** [comment] 2017-10-09 23:57
Thats what it looked like. thanks @dogboy21 Honestly tho I dont have much knowledge of how java code functions aside from basic stuff. I kinda just threw the code together from your commit and compiled. anything that this would possibly break?

**Comment by dogboy21** [comment] 2017-10-10 00:01
Nothing I know of. I've used this patch since the day the problems started and had no problems yet.
It just reverts a change made to the internal packet handling in 1.12 that doesn't allow negative packet ids which CoFH mods are using.

**Comment by popcorn9499** [comment] 2017-10-10 00:04
I am still unsure why they changed that. It worked so well before they did. I hope you dont mind that Ive been updating the commits added. do you?

**Comment by dogboy21** [comment] 2017-10-10 00:09
You've mentioned that these changes are not your own so I'm fine with this ^^

**Comment by popcorn9499** [comment] 2017-10-10 00:10
Ok thanks. Just figured that keeping it up to date would be nice since i already had it going I figured maybe it would help others here.

**Comment by Zilacon** [comment] 2017-10-29 19:24
@dogboy21 Where would i get this fixed version of yours? Ive been waiting half a year for this to get fixed so i can update. I REALLY need a working version of hexacord for 1.7.10.

Thanks.

**Comment by dogboy21** [comment] 2017-10-29 19:38
Look at [this comment](https://github.com/HexagonMC/BungeeCord/issues/152#issuecomment-335319626) from @popcorn9499. He has downloads for an updated version of my fix.

**Comment by Zilacon** [comment] 2017-10-29 19:43
Yeah i eventually found it soon after posting that.
Any idea what is causing this?
````
[B#353]  [12:41:27] [pool-4-thread-1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@47e9416b[id=43e54f6c-47d2-43cf-a133-cf020a5d337b,name=Zilacon,properties={},legacy=false]
[B#353]  com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
[B#353]  	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
[B#353]  	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [YggdrasilMinecraftSessionService.class:?]
[B#353]  	at net.minecraft.client.resources.SkinManager$3.run(SourceFile:106) [brm.class:?]
[B#353]  	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
[B#353]  	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
[B#353]  	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
[B#353]  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
[B#353]  	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
````

![screenshot_8](https://user-images.githubusercontent.com/3002248/32147548-8ad62e92-bca6-11e7-8b30-6ae666b63410.png)

I get this when trying to join my HUB using a 1.7.10 modpack. Besides this it looks like this versions working.

**Comment by dogboy21** [comment] 2017-10-29 20:10
> The client has sent too many requests within a certain amount of time

Rate Limiting of the Mojang Servers, happens when too many requests are made in a specific timeframe (10-15 minutes idk exactly)

> I get this when trying to join my HUB using a 1.7.10 modpack.

Might be a plugin on the server, haven't seen this error on our server

**Comment by popcorn9499** [comment] 2017-10-30 03:46
@dogboy21 This may just be a side effect of the patch but Id like to know weather you have any insight as to why id be getting "invalid payload register!" When i login to a spigot server with a modded client when using this patch. I dont remember having this before your patch that makes this work at all which dont get me wrong im really really greatful for but id like to know what i can do to make it work entirely. There r times when logging in quickly to my vanilla servers would be nice without having to load an entire new client up. Thanks

**Comment by NotixMLG** [comment] 2018-01-11 17:08
How to fix ?

**Comment by popcorn9499** [comment] 2018-01-11 22:49
@NotixMLG How to fix what? You need to be a little more specific or else I am not sure any of us here can help you.

**Comment by i9hdkill** [comment] 2018-07-31 20:00
This has been fixed lately

**Closed by i9hdkill** 2018-07-31 20:00 UTC
