### ISSUE TITLE
Client crash upon login, Could not get provider type..

### ISSUE THREAD

**Issue by CobaltSparkz** [HexagonMC/BungeeCord#53] opened 2016-07-16 00:34 UTC
Unfortunately, I seem to have an issue on my Forge Network, where, if a player logs into a non-default world on a modpack, such as a custom spawn world created with MultiWorld or MultiVerse, they will crash to the desktop with the error "could not get provider type for dimension(whatever), does not exist".

It seems to be that as these worlds are not part of the default modpack (I run FTB and ATL packs), that the client is not receiving the relevant DIM number/information, causing their client to crash.

Any ideas?

**Comment by MJRLegends** [comment] 2016-07-16 20:31
I can confirm im getting the same issue

**Comment by ghacproductions** [comment] 2016-07-16 23:04
Just to make sure, this is not happening when connecting directly to the server (without BungeeCord)?

**Comment by MJRLegends** [comment] 2016-07-16 23:05
Joining the not directly fixes the problem when it happens so nope it seems to only be when joining it directly

**Comment by CobaltSparkz** [comment] 2016-07-17 12:10
Joining directly, or via bungeecord causes the same issue - It's only on the plugin created worlds - I'm not massively knowledgeable, but I did hours of testing to see what the cause was, and it seems to be logging out in those "non-pack" worlds, that causes the crash.

**Comment by CobaltSparkz** [comment] 2016-07-21 17:40
To clarify, i've actually used around 6-7 completely different versions of Bungee, all with the same issue, only my current version, which I have no idea where I got it from, works =/

**Comment by MJRLegends** [comment] 2016-07-21 17:42
@cobaltsparkz you have a version that this is fixed in?

**Comment by CobaltSparkz** [comment] 2016-07-21 20:17
I do, yes - I have no idea where I got it from, but we've had it for months - It works with 1.7.10 clients and 1.8, HOWEVER, if you connect with Bungee, collecting Thaumcraft aspects doesn't work

**Comment by MJRLegends** [comment] 2016-07-21 20:17
So it doesnt work with 1.9?

**Comment by CobaltSparkz** [comment] 2016-07-21 20:19
Unfortunately not, no

**Comment by CobaltSparkz** [comment] 2016-07-21 20:20
I've tried HexagonMC's, Waterfall, Travertine, and various others, all with the same Dimension issue.

**Comment by MJRLegends** [comment] 2016-07-21 20:20
Great :(

**Comment by Proplex** [comment] 2016-07-22 02:43
So to confirm with anyone with this issue, if I am not using MultiVerse or generating any worlds outside of the modpack's (e.g. Mystcraft worlds, Twilight Forest worlds are still OK and do not crash), I am okay?

Would like to test this myself but I don't have any spare hardware to contribute to the cause.

**Comment by i9hdkill** [comment] 2016-07-22 02:45
Did you guys try BungeeCord from Yves mirror?

**Comment by CobaltSparkz** [comment] 2016-07-22 23:13
Yes, you are ok @Proplex - It's only "plugin" generated worlds, as the dimensions do not match up with the client, as it's not part of the "default" pack

**Comment by CobaltSparkz** [comment] 2016-07-26 17:50
@i9hdkill I believe I did, yes.

I essentially need a forge-supported Bungee client that supports 1.7.10 (Anything else I'm not using, so I'm not fussed) - As stated above, I've done a load of trials with various versions, all with the Dimension Crashing issue :'(

**Comment by CobaltSparkz** [comment] 2016-08-06 21:31
Still nothing that's working, anyone else with anything that works?

**Comment by Yann151924** [comment] 2016-08-14 14:07
I have the same issue on my server, i see an old pull request on the official bungeecord, i don't know if it can solve the problem, but i think it's a beginning, if you can take a look : https://github.com/SpigotMC/BungeeCord/pull/1283/files

**Comment by MJRLegends** [comment] 2016-08-23 13:30
@ghacproductions any news on this issue

**Comment by ghacproductions** [comment] 2016-08-23 13:41
I made some tests a while ago, unfortunately they were not successfull on the first tries. I'll look into this when I find some spare time.

**Comment by Yann151924** [comment] 2016-08-23 13:42
@MJRLegends I added Yive commit on the source code and I create a build with no error, (simply copy paste, it's bad i know), I will test tonight

**Comment by MJRLegends** [comment] 2016-08-23 13:54
@ghacproductions @Yann151924 ok just i really need a fix for this problem

**Comment by Yann151924** [comment] 2016-08-23 13:55
@MJRLegends Me too, i tp player to spawn on leave but it's not quite good for player experience :/

**Comment by MJRLegends** [comment] 2016-08-23 13:56
Yeah its giving me and my server staff a headache because they have to tp players out dimensions and that

**Comment by MJRLegends** [comment] 2016-08-23 14:01
So its broke in the normal version/official version of bungeecord too?

**Comment by ghacproductions** [comment] 2016-08-23 14:18
What modpacks(+ versions) are you using?

**Comment by Yann151924** [comment] 2016-08-23 14:20
I use different modpack ftb infinity 2.6 , or Agrarian Skies 2-1.1.14, or a custom modpack and always the same issue.

**Comment by MJRLegends** [comment] 2016-08-23 14:25
@ghacproductions Im using Space Astronomy which is my mod pack

**Comment by ghacproductions** [comment] 2016-08-23 23:21
@Yann151924 @MJRLegends Can one of you provide me a working server structure (e.g. one modpack with the libraries, mods and server-jars), so I can start looking into it a little more in detail.

**Comment by Yann151924** [comment] 2016-08-24 07:48
@ghacproductions for a ftb infinity i use this :
https://www.feed-the-beast.com/projects/ftb-infinity-evolved/files/2320899
And this :
http://tcpr.ca/files/thermos/Thermos-1.7.10-1614-56.zip

And after i use multiverse or multiworld to create custom world :
https://dev.bukkit.org/bukkit-plugins/multiverse-core/files/27-2-5-b691-beta/
https://dev.bukkit.org/bukkit-plugins/multiworld-v-2-0/files/76-v5-2-6/

**Comment by ghacproductions** [comment] 2016-08-24 11:14
I set up an environment similiar to yours, I have one lobby server (spigot only) and one FTB-server (Infinity 2.6). I created a new world with Multiverse on the FTB-server, changed to that world and disconnected completly from the server. After logging in again, I am at the same position on the newly created world where I logged out.

Are you having the issue with the client crashing when using a similiar setup to mine or have you a completly different setup?

**Comment by MJRLegends** [comment] 2016-08-24 11:24
I find its a random crash but if you use the bungeecord command for /server and go from the modded server to the hub then back to the modded server it does it

**Comment by ghacproductions** [comment] 2016-08-24 11:51
I tried that several times, on my end, it's not crashing.

**Comment by Yann151924** [comment] 2016-08-24 11:52
The bug doesn't appears at the beginning but when it's appears it will do all the time on login,

**Comment by MJRLegends** [comment] 2016-08-24 12:05
Yeah and mine does it every time with the /server command

**Comment by MJRLegends** [comment] 2016-08-24 12:12
@ghacproductions this is the crash/error i get for the /server command one http://pastebin.com/RQLPxcAb not sure if that one is bungeecord related but the other one is http://pastebin.com/ZyhUwkNz which is the login normally to a server when in another dimension other than vanilla ones

**Comment by MJRLegends** [comment] 2016-08-24 12:20
@ghacproductions for the first crash i said about there i just seems that the FMLNetworkEvent.ClientDisconnectionFromServerEvent event isnt running when changing servers using the command but the other crash idk what the issue is

**Comment by MJRLegends** [comment] 2016-08-24 12:26
@ghacproductions ignore my messages about the /server command thats a different issue and is a compact machines one i think

**Comment by ghacproductions** [comment] 2016-08-24 13:13
Can you check if your problem is equal to the one described here?

http://www.minecraftforum.net/forums/support/modded-client-support/2594789-crash-on-login-with-this-error

**Comment by MJRLegends** [comment] 2016-08-24 13:16
@ghacproductions yeah it is but mine is not on  "plotworld" or "mineworld" worlds its just any non vanilla dimension

**Comment by Yann151924** [comment] 2016-08-24 13:19
Same as @MJRLegends but on world created by mod like mystcraft or other i don't have any problem just appears with a world created by a plugin like multiverse or multiworld.

But when the server or not on bungee it's fine or when i used the Yive version of bungeecord i have no problem.

Look my post aboce apprently the problem come from the bungee, i found one pull request and the patch who Yive use.

**Comment by MJRLegends** [comment] 2016-08-24 13:20
@ghacproductions @Yann151924 mines with dimensions like compact machines and that

**Comment by Yann151924** [comment] 2016-08-24 13:21
Ho rip. I don't have the problem with the moded dimension

**Comment by MJRLegends** [comment] 2016-08-24 13:25
lucky but thats probably due to the mod pack your using, as it only seems to be the compact machine on for me

**Comment by ghacproductions** [comment] 2016-08-24 14:34
@Yann151924 can you try it with this version please:

https://www.dropbox.com/s/y2f4l99xg9xex6e/BungeeCord.jar?dl=0

**Comment by Yann151924** [comment] 2016-08-24 18:27
On test on my server, i will update if someone crash on the server

**Comment by MJRLegends** [comment] 2016-08-24 23:33
@Yann151924 still going good?

**Comment by MJRLegends** [comment] 2016-08-24 23:47
@ghacproductions @Yann151924 im now using it too so i will let you know how it does

**Comment by MJRLegends** [comment] 2016-08-25 00:15
@ghacproductions nope still getting the crash issue

**Comment by Yann151924** [comment] 2016-08-25 06:06
Don't have the crash for me i'm waiting :)

**Comment by ghacproductions** [comment] 2016-08-25 12:19
@Yann151924 If it's working for the next, let's say 6 hours, I would say, that your problem is fixed. 

@MJRLegends I guess your issue is not exactly the same, so it might be very diffucult to fix your problem.

**Comment by MJRLegends** [comment] 2016-08-25 12:22
@ghacproductions well mine seems to be the compact machines dimension and its only happened once so far and apparently it happened before the build you posted here was used on my bungeecord so maybe it is fixed?

**Comment by Yann151924** [comment] 2016-08-25 12:31
@ghacproductions Ok no client crash for the moment i wait tonight when the player login :)

**Comment by MJRLegends** [comment] 2016-08-25 15:38
@ghacproductions yeah im still getting the issue :(

**Comment by MJRLegends** [comment] 2016-08-25 21:31
@ghacproductions thanks for your time, i've sorted the issue and your changes were great :D

**Comment by Yann151924** [comment] 2016-08-26 07:58
@ghacproductions Thanks for fixing the issue :)

**Comment by MJRLegends** [comment] 2016-08-26 10:48
Are you going to merge the changes to fix this issue with the main branch?

**Comment by ghacproductions** [comment] 2016-08-26 14:29
I've merged it into the master-branch, see 

https://github.com/HexagonMC/BungeeCord/commit/20c12f2fa8a0a3370308053c659d07555a3cff9b

**Closed by ghacproductions** 2016-08-26 14:29 UTC

**Comment by MJRLegends** [comment] 2016-08-26 15:57
@ghacproductions i seem to have got the issue just a min ago but it only seem to be when connecting from the hub and not direct ip's
The hub is 1.7.10 and these are the plugins it contains any ideas?
![](https://i.gyazo.com/1bfbf3f999ca4852414b1b1dac8145ac.png)

**Comment by ghacproductions** [comment] 2016-08-26 16:00
@MJRLegends What exactly have you done?

**Comment by MJRLegends** [comment] 2016-08-26 16:04
@ghacproductions Well i was using the protocol support plugin with a 1.9.4 server but i made a 1.7.10 hub as the mod pack servers are 1.7.10 and removed the protocol support plugin and now two players just reported they couldnt join and showed me the crash log and then i asked them to use the direct ips to connect and it worked great but not from the hub

Issue they posted to me: https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/503

**Comment by MJRLegends** [comment] 2016-08-26 16:05
Also im still using the self complied version of bungeecord you posted here, would that be why?

**Comment by MJRLegends** [comment] 2016-08-26 16:09
@ghacproductions Also i dont know if this is why but i keep getting this error when the modded server (the one the error is linked to) is starting up http://pastebin.com/aPb4YPXB

**Comment by CobaltSparkz** [comment] 2016-08-28 23:10
To clarify, the build you've posted supports WHICH Versions of minecraft? :)

**Comment by ghacproductions** [comment] 2016-08-29 08:46
@CobaltSparkz All builds (the one I posted here and the builds from the releases Tab) should support versions 1.7 to 1.10)

**Comment by CobaltSparkz** [comment] 2016-10-29 19:58
Apologies for the late reply - 
Awesome, thanks @ghacproductions - I tried using Hexagon before, as it was highly recommended, but never got anywhere, had the same issue. I'll try this version and let you know the outcome :)

**Comment by CobaltSparkz** [comment] 2016-11-21 20:20
An update - It seems to work for the most part, but some people are now reporting that's it's happening again o.o

**Comment by i9hdkill** [comment] 2016-11-21 20:36
Which build?

**Comment by CobaltSparkz** [comment] 2016-11-21 20:58
https://www.dropbox.com/s/y2f4l99xg9xex6e/BungeeCord.jar?dl=0 (the version from higher up) - I wasn't sure if I could/should use the newest version, as I wasn't aware if any "custom" changes had been made
