### ISSUE TITLE
Latest version bad packet ID.

### ISSUE THREAD

**Issue by rippin** [HexagonMC/BungeeCord#35] opened 2016-05-14 06:34 UTC
While I can login with 1.7-1.9.4 my console is being spammed by this 
http://pastebin.com/FPZqUcgL

**Comment by i9hdkill** [comment] 2016-05-14 11:31
Did you check every single version? We are running this on an server with 150 people online that are using clients from forge 1.7.10 to 1.9.4 and we are not experiencing this problem.

Can you reproduce this with your own client? If yes, which version?
Looks like an old Version of ProtocolSupport or ProtocolsupportBungee.

**Comment by Zartec** [comment] 2016-05-15 10:44
Possible fixed by #36

**Comment by i9hdkill** [comment] 2016-05-19 14:15
Closing this, as this was fixed upstream.

**Closed by i9hdkill** 2016-05-19 14:15 UTC
Labels: waiting for information
